### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GhostV-Survival** [iSheesho/qb-communityservice#2]
[script:qb-communitys] SCRIPT ERROR: @qb-communityservice/server/main.lua:134: attempt to index a nil value

Getting this after serverstart

**Comment by bbishop56** [comment]
Same here

**Comment by Rayzer567** [comment]
same and when i leave the server the tasks are removed

**Comment by Belorico** [comment]
![image](https://user-images.githubusercontent.com/4929196/163296671-b2d5b5d1-ae36-4aef-853c-ef1e32c26394.png)

Also getting the error

**Comment by strongprincess** [comment]
im experencing the same error and when my fivem crashed i rejoined had no actions when i came back

**Comment by iSheesho** [comment]
Fixed in v1.2
