### ISSUE TITLE
Cleaning Animation

### ISSUE THREAD

**Issue by Asmoddy** [iSheesho/qb-communityservice#3]
Whenever I do cleaning while on comserv, my character just stand and does nothing but hold a broom. Is there a fix for this?

**Comment by iSheesho** [comment]
Sure, that's how it should work, I didn't find a way to do the ESX -> QBcore conversion of the sweep animation with the broom prop in hand

**Comment by z0nzjn123** [comment]
This PR of mine will solve this problem
https://github.com/iSheesho/qb-communityservice/pull/4

**Comment by Andyauk** [comment]
> This PR of mine will solve this problem #4

no it still crashes, fivem when you goto start cleaning.

**Comment by z0nzjn123** [comment]
> > This PR of mine will solve this problem #4
> 
> no it still crashes, fivem when you goto start cleaning.

work fine for me
