### ISSUE TITLE
FiveM crashes when animation starts

### ISSUE THREAD

**Issue by Jissuunnn** [iSheesho/qb-communityservice#9]
There's this error on the console that I don't understand what it is, and once I start the animation of the service, FiveM freezes then it crashes after a few seconds. 

![image](https://user-images.githubusercontent.com/83680775/180649114-957627e3-f7d2-4a00-bbaf-a2fde90a12d2.png)

**Comment by iSheesho** [comment]
Download the latest version!

**Comment by Jissuunnn** [comment]
well that fixed it. The only problem now is the animations. Big thanks and sorry for the trouble!
